% GRIDGUARD AI — Smart City Electrical Digital Twin
% Data Logging & Export Utility: export_gridguard_data.m
%
% Exports all time-series digital twin metrics, electrical signals, zone statuses,
% and controller actions to MATLAB Tables, MAT files, and CSV files.

function log_table = export_gridguard_data(sim_data, output_filename)

    if nargin < 2
        output_filename = 'gridguard_simulation_results.csv';
    end

    fprintf('=====================================================\n');
    fprintf('  GRIDGUARD AI: Exporting Digital Twin Data Logs...  \n');
    fprintf('=====================================================\n');

    % Extract arrays from simulation structure
    time_s = sim_data.time;
    v_grid_pu = sim_data.v_grid_pu;
    freq_hz = sim_data.freq_hz;
    p_gen_mw = sim_data.p_gen_mw;
    p_load_mw = sim_data.p_load_mw;
    p_solar_mw = sim_data.p_solar_mw;
    p_wind_mw = sim_data.p_wind_mw;
    bess_soc_pct = sim_data.bess_soc_pct;
    bess_power_mw = sim_data.bess_power_mw;
    ev_demand_mw = sim_data.ev_demand_mw;
    ghi_pct = sim_data.ghi_pct;
    ctrl_state = sim_data.ctrl_state;
    fault_code = sim_data.fault_code;
    anomaly_score = sim_data.anomaly_score;

    % Build MATLAB Table
    log_table = table( ...
        time_s, ...
        v_grid_pu, ...
        freq_hz, ...
        p_gen_mw, ...
        p_load_mw, ...
        p_solar_mw, ...
        p_wind_mw, ...
        bess_soc_pct, ...
        bess_power_mw, ...
        ev_demand_mw, ...
        ghi_pct, ...
        ctrl_state, ...
        fault_code, ...
        anomaly_score, ...
        'VariableNames', { ...
            'Timestamp_s', 'Voltage_pu', 'Frequency_Hz', ...
            'TotalGen_MW', 'TotalLoad_MW', 'SolarGen_MW', 'WindGen_MW', ...
            'BESS_SOC_Pct', 'BESS_Power_MW', 'EVDemand_MW', ...
            'GridHealthIndex_Pct', 'ControllerState', 'FaultCode', 'AI_AnomalyScore' ...
        } ...
    );

    % Export to MAT File
    mat_filename = strrep(output_filename, '.csv', '.mat');
    save(mat_filename, 'log_table', 'sim_data');
    fprintf('  Logged %d time-series records to %s\n', height(log_table), mat_filename);

    % Export to CSV File
    writetable(log_table, output_filename);
    fprintf('  Successfully exported CSV log: %s\n', output_filename);
    fprintf('=====================================================\n\n');

end
