/* Generated by Yosys 0.69+73 (git sha1 2e7d8006d-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:7.1-35.10" *)
module alarm_controller(clk, reset, gsi, blackout_risk_indicator, fault_detected, warning_alarm, critical_alarm, emergency_alarm);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:8.24-8.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:9.24-9.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:10.24-10.27" *)
  input [7:0] gsi;
  wire [7:0] gsi;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:11.24-11.47" *)
  input [7:0] blackout_risk_indicator;
  wire [7:0] blackout_risk_indicator;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:12.24-12.38" *)
  input fault_detected;
  wire fault_detected;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:13.24-13.37" *)
  output warning_alarm;
  reg warning_alarm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:14.24-14.38" *)
  output critical_alarm;
  reg critical_alarm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:15.24-15.39" *)
  output emergency_alarm;
  reg emergency_alarm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:18.5-33.8" *)
  wire _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:18.5-33.8" *)
  wire _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:18.5-33.8" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  assign _03_ = gsi[0] | gsi[2];
  assign _04_ = gsi[1] | gsi[2];
  assign _13_ = blackout_risk_indicator[6] & _12_;
  assign _14_ = ~(_11_ & _13_);
  assign _15_ = blackout_risk_indicator[4] | blackout_risk_indicator[5];
  assign _16_ = ~(blackout_risk_indicator[6] & _15_);
  assign _17_ = ~(gsi[7] | blackout_risk_indicator[7]);
  assign _18_ = _16_ & _17_;
  assign _19_ = _14_ & _18_;
  assign _00_ = ~(_09_ & _19_);
  assign _20_ = gsi[3] | _04_;
  assign _21_ = gsi[4] & gsi[5];
  assign _05_ = gsi[3] & _04_;
  assign _22_ = ~(_20_ & _21_);
  assign _23_ = ~(gsi[6] | gsi[7]);
  assign _24_ = _23_ & ~(fault_detected);
  assign _02_ = ~(_22_ & _24_);
  assign _25_ = ~(gsi[4] & _05_);
  assign _26_ = ~(gsi[5] | gsi[7]);
  assign _27_ = _25_ & _26_;
  assign _28_ = _23_ | _27_;
  assign _29_ = blackout_risk_indicator[5] | _11_;
  assign _30_ = _29_ & ~(_16_);
  assign _06_ = ~(_03_ & _05_);
  assign _31_ = ~(blackout_risk_indicator[7] | _30_);
  assign _01_ = ~(_28_ & _31_);
  assign _07_ = ~(gsi[4] | gsi[5]);
  assign _08_ = ~(_06_ & _07_);
  assign _09_ = ~(gsi[6] & _08_);
  assign _10_ = blackout_risk_indicator[1] | blackout_risk_indicator[2];
  assign _11_ = blackout_risk_indicator[3] & _10_;
  assign _12_ = blackout_risk_indicator[0] | blackout_risk_indicator[2];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:18.5-33.8" *)
  always @(posedge clk, posedge reset)
    if (reset) warning_alarm <= 1'h0;
    else warning_alarm <= _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:18.5-33.8" *)
  always @(posedge clk, posedge reset)
    if (reset) critical_alarm <= 1'h0;
    else critical_alarm <= _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/alarm_controller.v:18.5-33.8" *)
  always @(posedge clk, posedge reset)
    if (reset) emergency_alarm <= 1'h0;
    else emergency_alarm <= _01_;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:7.1-46.10" *)
module battery_monitor(clk, reset, battery_soc, battery_available, battery_low, battery_critical, battery_ready_for_support);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:11.24-11.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:12.24-12.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:13.24-13.35" *)
  input [15:0] battery_soc;
  wire [15:0] battery_soc;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:14.24-14.41" *)
  output battery_available;
  reg battery_available;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:15.24-15.35" *)
  output battery_low;
  reg battery_low;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:16.24-16.40" *)
  output battery_critical;
  reg battery_critical;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:17.24-17.49" *)
  output battery_ready_for_support;
  reg battery_ready_for_support;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:20.5-44.8" *)
  wire _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:20.5-44.8" *)
  wire _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:20.5-44.8" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* force_downto = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:27.17-27.44|d:\\gridguard\\oss-cad-suite\\bin\\../share/yosys/techmap.v:274.23-274.25" *)
  wire [13:0] _17_;
  assign _03_ = ~(battery_soc[9] | battery_soc[7]);
  assign _04_ = ~(battery_soc[8] | battery_soc[6]);
  assign _13_ = battery_soc[4] & _12_;
  assign _14_ = ~(battery_soc[5] | _13_);
  assign _00_ = _11_ & _14_;
  assign _17_[13] = ~(_11_ & _14_);
  assign _15_ = battery_soc[4] | battery_soc[3];
  assign _16_ = ~(battery_soc[5] & _15_);
  assign _01_ = _11_ & _16_;
  assign _02_ = ~(_11_ & _16_);
  assign _05_ = _03_ & _04_;
  assign _06_ = ~(battery_soc[15] | battery_soc[14]);
  assign _07_ = ~(battery_soc[13] | battery_soc[11]);
  assign _08_ = ~(battery_soc[12] | battery_soc[10]);
  assign _09_ = _07_ & _08_;
  assign _10_ = _06_ & _09_;
  assign _11_ = _05_ & _10_;
  assign _12_ = battery_soc[3] | battery_soc[2];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:20.5-44.8" *)
  always @(posedge clk, posedge reset)
    if (reset) battery_available <= 1'h1;
    else battery_available <= _17_[13];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:20.5-44.8" *)
  always @(posedge clk, posedge reset)
    if (reset) battery_low <= 1'h0;
    else battery_low <= _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:20.5-44.8" *)
  always @(posedge clk, posedge reset)
    if (reset) battery_critical <= 1'h0;
    else battery_critical <= _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/battery_monitor.v:20.5-44.8" *)
  always @(posedge clk, posedge reset)
    if (reset) battery_ready_for_support <= 1'h1;
    else battery_ready_for_support <= _02_;
  assign _17_[0] = battery_soc[2];
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:9.1-55.10" *)
module blackout_risk(clk, reset, gsi, voltage_critical, frequency_critical, transformer_overload, ev_surge, solar_drop, battery_available, blackout_risk_indicator);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:10.24-10.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:11.24-11.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:12.24-12.27" *)
  input [7:0] gsi;
  wire [7:0] gsi;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:13.24-13.40" *)
  input voltage_critical;
  wire voltage_critical;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:14.24-14.42" *)
  input frequency_critical;
  wire frequency_critical;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:15.24-15.44" *)
  input transformer_overload;
  wire transformer_overload;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:16.24-16.32" *)
  input ev_surge;
  wire ev_surge;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:17.24-17.34" *)
  input solar_drop;
  wire solar_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:18.24-18.41" *)
  input battery_available;
  wire battery_available;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:19.24-19.47" *)
  output [7:0] blackout_risk_indicator;
  wire [7:0] blackout_risk_indicator;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  assign _018_ = ev_surge & solar_drop;
  assign _019_ = ~(voltage_critical & frequency_critical);
  assign _028_ = gsi[0] | _027_;
  assign _029_ = ~(gsi[0] ^ _026_);
  assign _030_ = ~(_018_ & _029_);
  assign _031_ = _018_ ^ _029_;
  assign _032_ = gsi[0] | gsi[1];
  assign _033_ = gsi[3] & gsi[2];
  assign _034_ = _032_ & _033_;
  assign _035_ = ~(gsi[4] & _034_);
  assign _036_ = gsi[5] | ~(_035_);
  assign _037_ = _026_ & _036_;
  assign _020_ = ~(voltage_critical ^ frequency_critical);
  assign _038_ = ~(transformer_overload & _023_);
  assign _039_ = _038_ & ~(_022_);
  assign _040_ = gsi[2] & gsi[1];
  assign _041_ = gsi[3] | _040_;
  assign _042_ = _025_ & _039_;
  assign _043_ = _041_ & _042_;
  assign _044_ = ~(gsi[4] & _043_);
  assign _045_ = _039_ & _044_;
  assign _046_ = gsi[4] | _033_;
  assign _047_ = ~(_027_ & _046_);
  assign _021_ = battery_available | _020_;
  assign _048_ = _039_ ? _044_ : _047_;
  assign _049_ = gsi[5] & ~(_048_);
  assign _050_ = _037_ | _049_;
  assign _051_ = gsi[6] & _050_;
  assign _052_ = ~(gsi[7] | _051_);
  assign _053_ = gsi[4] | _043_;
  assign _054_ = ~(_045_ & _053_);
  assign _055_ = gsi[4] ^ _033_;
  assign _056_ = _039_ | _055_;
  assign _057_ = ~(_054_ & _056_);
  assign _022_ = ~(_019_ & _021_);
  assign _058_ = ~(_027_ & _057_);
  assign _059_ = _026_ & _035_;
  assign _060_ = gsi[4] | _034_;
  assign _061_ = ~(_059_ & _060_);
  assign _062_ = ~(_058_ & _061_);
  assign _063_ = _040_ | ~(_042_);
  assign _064_ = _039_ | ~(gsi[2]);
  assign _065_ = ~(_063_ & _064_);
  assign _066_ = ~(_027_ & _065_);
  assign _067_ = _026_ & _032_;
  assign _023_ = ~(battery_available & _020_);
  assign _068_ = ~(gsi[2] & _067_);
  assign _069_ = _066_ & _068_;
  assign _070_ = ~(gsi[3] ^ _069_);
  assign _071_ = _028_ & ~(_042_);
  assign _072_ = ~(gsi[1] ^ _071_);
  assign _073_ = _029_ & ~(_072_);
  assign _074_ = ~(gsi[1] & _025_);
  assign _075_ = ~(_039_ & _074_);
  assign _076_ = _027_ ? _075_ : _032_;
  assign _077_ = gsi[2] ^ _076_;
  assign _024_ = _021_ & _023_;
  assign _078_ = _073_ & ~(_077_);
  assign _079_ = _070_ | ~(_078_);
  assign _080_ = _018_ & _079_;
  assign _081_ = _062_ & _080_;
  assign _082_ = _048_ & ~(_059_);
  assign _083_ = ~(gsi[5] ^ _082_);
  assign _084_ = _081_ & _083_;
  assign _085_ = gsi[6] ^ _050_;
  assign _086_ = ~(_084_ & _085_);
  assign _087_ = ~(gsi[7] ^ _051_);
  assign _025_ = transformer_overload | _024_;
  assign _088_ = _052_ & _086_;
  assign _089_ = _081_ ^ _083_;
  assign _090_ = ~(_062_ ^ _080_);
  assign _091_ = _030_ | _072_;
  assign _092_ = ~(_077_ | _091_);
  assign _093_ = ~(_077_ ^ _091_);
  assign _001_ = ~(_070_ | _093_);
  assign _002_ = ~(_090_ & _001_);
  assign _003_ = _089_ & _002_;
  assign _004_ = _084_ ^ _085_;
  assign _026_ = _022_ & _025_;
  assign _005_ = ~(_003_ & _004_);
  assign _006_ = ~(_088_ & _005_);
  assign _007_ = ~(_070_ ^ _092_);
  assign _008_ = _031_ & _077_;
  assign _009_ = _008_ & ~(_072_);
  assign _010_ = _087_ & _009_;
  assign _011_ = _007_ & _010_;
  assign _012_ = _090_ & _011_;
  assign _013_ = _089_ & _012_;
  assign _014_ = ~(_004_ & _013_);
  assign _027_ = ~(_022_ & _025_);
  assign _015_ = _006_ & _014_;
  assign _016_ = ~(_006_ & _014_);
  assign _000_[0] = ~(_031_ | _015_);
  assign _017_ = ~(_030_ ^ _072_);
  assign _000_[1] = _016_ & _017_;
  assign _000_[2] = _093_ | _015_;
  assign _000_[3] = ~(_006_ | _007_);
  assign _000_[4] = ~(_090_ | _006_);
  assign _000_[5] = _089_ | _006_;
  assign _000_[6] = _004_ | ~(_088_);
  reg \blackout_risk_indicator_reg[0] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \blackout_risk_indicator_reg[0]  <= 1'h0;
    else \blackout_risk_indicator_reg[0]  <= _000_[0];
  assign blackout_risk_indicator[0] = \blackout_risk_indicator_reg[0] ;
  reg \blackout_risk_indicator_reg[1] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \blackout_risk_indicator_reg[1]  <= 1'h0;
    else \blackout_risk_indicator_reg[1]  <= _000_[1];
  assign blackout_risk_indicator[1] = \blackout_risk_indicator_reg[1] ;
  reg \blackout_risk_indicator_reg[2] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \blackout_risk_indicator_reg[2]  <= 1'h0;
    else \blackout_risk_indicator_reg[2]  <= _000_[2];
  assign blackout_risk_indicator[2] = \blackout_risk_indicator_reg[2] ;
  reg \blackout_risk_indicator_reg[3] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \blackout_risk_indicator_reg[3]  <= 1'h0;
    else \blackout_risk_indicator_reg[3]  <= _000_[3];
  assign blackout_risk_indicator[3] = \blackout_risk_indicator_reg[3] ;
  reg \blackout_risk_indicator_reg[4] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \blackout_risk_indicator_reg[4]  <= 1'h0;
    else \blackout_risk_indicator_reg[4]  <= _000_[4];
  assign blackout_risk_indicator[4] = \blackout_risk_indicator_reg[4] ;
  reg \blackout_risk_indicator_reg[5] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \blackout_risk_indicator_reg[5]  <= 1'h0;
    else \blackout_risk_indicator_reg[5]  <= _000_[5];
  assign blackout_risk_indicator[5] = \blackout_risk_indicator_reg[5] ;
  reg \blackout_risk_indicator_reg[6] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/blackout_risk.v:26.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \blackout_risk_indicator_reg[6]  <= 1'h0;
    else \blackout_risk_indicator_reg[6]  <= _000_[6];
  assign blackout_risk_indicator[6] = \blackout_risk_indicator_reg[6] ;
  assign _000_[7] = 1'h0;
  assign blackout_risk_indicator[7] = 1'h0;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:9.1-35.10" *)
module critical_load_protection(clk, reset, gsi, reduce_noncritical_load, preserve_critical_load, hospital_feeder_status, water_plant_feeder_status, datacenter_feeder_status);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:10.24-10.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:11.24-11.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:12.24-12.27" *)
  input [7:0] gsi;
  wire [7:0] gsi;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:13.24-13.47" *)
  input reduce_noncritical_load;
  wire reduce_noncritical_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:14.24-14.46" *)
  output preserve_critical_load;
  wire preserve_critical_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:15.24-15.46" *)
  output hospital_feeder_status;
  wire hospital_feeder_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:16.24-16.49" *)
  output water_plant_feeder_status;
  wire water_plant_feeder_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/critical_load_protection.v:17.24-17.48" *)
  output datacenter_feeder_status;
  wire datacenter_feeder_status;
  assign datacenter_feeder_status = 1'h1;
  assign water_plant_feeder_status = 1'h1;
  assign hospital_feeder_status = 1'h1;
  assign preserve_critical_load = 1'h1;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:7.1-41.10" *)
module ev_load_monitor(clk, reset, ev_charging_load, ev_normal, ev_high, ev_surge);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:11.24-11.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:12.24-12.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:13.24-13.40" *)
  input [15:0] ev_charging_load;
  wire [15:0] ev_charging_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:14.24-14.33" *)
  output ev_normal;
  reg ev_normal;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:15.24-15.31" *)
  output ev_high;
  wire ev_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:16.24-16.32" *)
  output ev_surge;
  reg ev_surge;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  wire _000_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:19.16-19.28" *)
  reg [15:0] prev_ev_load;
  assign _069_ = prev_ev_load[14] | ~(ev_charging_load[14]);
  assign _070_ = ev_charging_load[7] | ~(prev_ev_load[7]);
  assign _079_ = ~(_077_ & _078_);
  assign _037_ = ~(_124_ ^ _036_);
  assign _038_ = _035_ & ~(_037_);
  assign _039_ = _032_ & _038_;
  assign _040_ = ~(_006_ & _039_);
  assign _041_ = ~(_002_ & _003_);
  assign _042_ = _086_ & _127_;
  assign _043_ = _016_ & _042_;
  assign _044_ = _132_ & _005_;
  assign _045_ = _020_ & _044_;
  assign _046_ = prev_ev_load[0] | ~(ev_charging_load[0]);
  assign _080_ = prev_ev_load[3] | ~(ev_charging_load[3]);
  assign _047_ = _081_ & _087_;
  assign _048_ = _046_ & _047_;
  assign _049_ = ~(_072_ & _076_);
  assign _050_ = ~(_090_ | _049_);
  assign _051_ = _048_ & _050_;
  assign _052_ = _045_ & _051_;
  assign _053_ = _113_ & _052_;
  assign _054_ = ~(_043_ & _053_);
  assign _055_ = _004_ & _054_;
  assign _056_ = _041_ & _055_;
  assign _081_ = prev_ev_load[4] | ~(ev_charging_load[4]);
  assign _057_ = ~(_040_ & _056_);
  assign _058_ = ev_charging_load[9] & ev_charging_load[8];
  assign _059_ = ev_charging_load[10] & _058_;
  assign _060_ = ev_charging_load[4] | ev_charging_load[5];
  assign _061_ = ev_charging_load[7] & ev_charging_load[6];
  assign _062_ = _060_ & _061_;
  assign _063_ = ~(_059_ & _062_);
  assign _064_ = ~(ev_charging_load[13] | ev_charging_load[15]);
  assign _065_ = ~(ev_charging_load[11] | ev_charging_load[14]);
  assign _066_ = _065_ & ~(ev_charging_load[12]);
  assign _082_ = _080_ & _081_;
  assign _067_ = _064_ & _066_;
  assign _068_ = _063_ & _067_;
  assign _001_ = _057_ & _068_;
  assign _000_ = ~(_057_ & _068_);
  assign _083_ = _079_ & _082_;
  assign _084_ = _077_ & _080_;
  assign _085_ = ~(prev_ev_load[2] ^ ev_charging_load[2]);
  assign _086_ = _084_ & _085_;
  assign _087_ = prev_ev_load[1] | ~(ev_charging_load[1]);
  assign _088_ = ev_charging_load[0] | ~(prev_ev_load[0]);
  assign _071_ = prev_ev_load[6] | ~(ev_charging_load[6]);
  assign _089_ = ev_charging_load[1] | ~(prev_ev_load[1]);
  assign _090_ = ~(_088_ & _089_);
  assign _091_ = ~(_087_ & _090_);
  assign _092_ = ~(_086_ & _091_);
  assign _093_ = ~(_083_ & _092_);
  assign _094_ = ~(_076_ & _093_);
  assign _095_ = ~(_075_ & _094_);
  assign _096_ = _074_ & _095_;
  assign _097_ = ~(_073_ & _096_);
  assign _098_ = prev_ev_load[7] | ~(ev_charging_load[7]);
  assign _072_ = ev_charging_load[6] | ~(prev_ev_load[6]);
  assign _099_ = _071_ & _098_;
  assign _100_ = ~(_097_ & _099_);
  assign _101_ = _070_ & _100_;
  assign _102_ = prev_ev_load[9] | ~(ev_charging_load[9]);
  assign _103_ = ~(prev_ev_load[9] ^ ev_charging_load[9]);
  assign _104_ = ev_charging_load[8] & ~(prev_ev_load[8]);
  assign _105_ = ~(prev_ev_load[8] ^ ev_charging_load[8]);
  assign _106_ = _103_ & _105_;
  assign _107_ = prev_ev_load[11] | ~(ev_charging_load[11]);
  assign _108_ = ev_charging_load[11] | ~(prev_ev_load[11]);
  assign _073_ = _071_ & _072_;
  assign _109_ = _107_ & _108_;
  assign _110_ = ev_charging_load[10] & ~(prev_ev_load[10]);
  assign _111_ = ~(prev_ev_load[10] ^ ev_charging_load[10]);
  assign _112_ = _109_ & _111_;
  assign _113_ = _106_ & _112_;
  assign _114_ = ~(_101_ & _113_);
  assign _115_ = ~(_103_ & _104_);
  assign _116_ = _102_ & _115_;
  assign _117_ = _116_ | ~(_112_);
  assign _118_ = ~(_108_ & _110_);
  assign _074_ = ev_charging_load[5] | ~(prev_ev_load[5]);
  assign _119_ = _107_ & _118_;
  assign _120_ = _117_ & _119_;
  assign _121_ = ~(_114_ & _120_);
  assign _122_ = ev_charging_load[13] | ~(prev_ev_load[13]);
  assign _123_ = prev_ev_load[13] | ~(ev_charging_load[13]);
  assign _124_ = _122_ & _123_;
  assign _125_ = prev_ev_load[12] | ~(ev_charging_load[12]);
  assign _126_ = ~(prev_ev_load[12] ^ ev_charging_load[12]);
  assign _127_ = _124_ & _126_;
  assign _128_ = ~(_121_ & _127_);
  assign _075_ = prev_ev_load[5] | ~(ev_charging_load[5]);
  assign _129_ = ~(_123_ & _125_);
  assign _130_ = ~(_122_ & _129_);
  assign _131_ = ~(_128_ & _130_);
  assign _132_ = ~(prev_ev_load[14] ^ ev_charging_load[14]);
  assign _133_ = ~(_131_ & _132_);
  assign _002_ = _069_ & _133_;
  assign _003_ = prev_ev_load[15] | ~(ev_charging_load[15]);
  assign _004_ = ev_charging_load[15] | ~(prev_ev_load[15]);
  assign _005_ = _003_ & _004_;
  assign _006_ = _002_ | _005_;
  assign _076_ = ev_charging_load[4] | ~(prev_ev_load[4]);
  assign _007_ = ~(_101_ & _106_);
  assign _008_ = ~(_116_ & _007_);
  assign _009_ = _111_ & _008_;
  assign _010_ = ~(_111_ ^ _008_);
  assign _011_ = ~(_121_ & _126_);
  assign _012_ = ~(_121_ ^ _126_);
  assign _013_ = ~(_101_ & _105_);
  assign _014_ = _101_ | _105_;
  assign _015_ = _070_ & _098_;
  assign _016_ = _071_ & _015_;
  assign _077_ = ev_charging_load[3] | ~(prev_ev_load[3]);
  assign _017_ = ~(_073_ | _016_);
  assign _018_ = _096_ ? _073_ : _017_;
  assign _019_ = _072_ & ~(_015_);
  assign _020_ = _074_ & _075_;
  assign _021_ = ~(_094_ ^ _020_);
  assign _022_ = ~(_019_ | _021_);
  assign _023_ = ~(_018_ & _022_);
  assign _024_ = _103_ ^ _104_;
  assign _025_ = _023_ & _024_;
  assign _026_ = _014_ & _025_;
  assign _078_ = ev_charging_load[2] & ~(prev_ev_load[2]);
  assign _027_ = ~(_013_ & _026_);
  assign _028_ = _010_ & _027_;
  assign _029_ = _012_ & _028_;
  assign _030_ = ~(_110_ | _009_);
  assign _031_ = ~(_109_ ^ _030_);
  assign _032_ = _029_ & ~(_031_);
  assign _033_ = _069_ & _005_;
  assign _034_ = ~(_132_ | _033_);
  assign _035_ = _131_ ? _132_ : _034_;
  assign _036_ = _125_ & _011_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) ev_normal <= 1'h1;
    else ev_normal <= _001_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) ev_surge <= 1'h0;
    else ev_surge <= _000_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[0] <= 1'h0;
    else prev_ev_load[0] <= ev_charging_load[0];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[1] <= 1'h0;
    else prev_ev_load[1] <= ev_charging_load[1];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[2] <= 1'h0;
    else prev_ev_load[2] <= ev_charging_load[2];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[3] <= 1'h0;
    else prev_ev_load[3] <= ev_charging_load[3];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[4] <= 1'h1;
    else prev_ev_load[4] <= ev_charging_load[4];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[5] <= 1'h1;
    else prev_ev_load[5] <= ev_charging_load[5];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[6] <= 1'h0;
    else prev_ev_load[6] <= ev_charging_load[6];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[7] <= 1'h1;
    else prev_ev_load[7] <= ev_charging_load[7];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[8] <= 1'h0;
    else prev_ev_load[8] <= ev_charging_load[8];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[9] <= 1'h0;
    else prev_ev_load[9] <= ev_charging_load[9];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[10] <= 1'h1;
    else prev_ev_load[10] <= ev_charging_load[10];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[11] <= 1'h0;
    else prev_ev_load[11] <= ev_charging_load[11];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[12] <= 1'h0;
    else prev_ev_load[12] <= ev_charging_load[12];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[13] <= 1'h0;
    else prev_ev_load[13] <= ev_charging_load[13];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[14] <= 1'h0;
    else prev_ev_load[14] <= ev_charging_load[14];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/ev_load_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_ev_load[15] <= 1'h0;
    else prev_ev_load[15] <= ev_charging_load[15];
  assign ev_high = ev_surge;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:7.1-73.10" *)
module fault_detector(clk, reset, voltage_low, voltage_high, frequency_critical, frequency_high, transformer_overload, ev_surge, solar_drop, fault_injection_sig, fault_detected, fault_code);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:8.23-8.26" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:10.23-10.34" *)
  input voltage_low;
  wire voltage_low;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:11.23-11.35" *)
  input voltage_high;
  wire voltage_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:12.23-12.41" *)
  input frequency_critical;
  wire frequency_critical;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:13.23-13.37" *)
  input frequency_high;
  wire frequency_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:14.23-14.43" *)
  input transformer_overload;
  wire transformer_overload;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:15.23-15.31" *)
  input ev_surge;
  wire ev_surge;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:16.23-16.33" *)
  input solar_drop;
  wire solar_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:17.23-17.42" *)
  input fault_injection_sig;
  wire fault_injection_sig;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:18.23-18.37" *)
  output fault_detected;
  reg fault_detected;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:19.23-19.33" *)
  output [3:0] fault_code;
  reg [3:0] fault_code;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:37.5-71.8" *)
  wire [3:0] _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:37.5-71.8" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:33.16-33.25" *)
  wire [3:0] fault_sum;
  assign _02_ = voltage_high | voltage_low;
  assign _03_ = transformer_overload | _02_;
  assign _12_ = _10_ & _11_;
  assign _13_ = ~(ev_surge & _05_);
  assign _14_ = _09_ & _12_;
  assign _15_ = _08_ & _14_;
  assign _16_ = _07_ & _15_;
  assign _17_ = _13_ & _16_;
  assign _00_[3] = ~_17_;
  assign _18_ = ~(solar_drop | ev_surge);
  assign _19_ = ~(frequency_high | transformer_overload);
  assign _20_ = _18_ & _19_;
  assign _04_ = fault_injection_sig | _03_;
  assign _21_ = ~(voltage_high | frequency_critical);
  assign _22_ = ~(voltage_low | fault_injection_sig);
  assign _23_ = _21_ & _22_;
  assign _01_ = ~(_20_ & _23_);
  assign _24_ = solar_drop & ~(ev_surge);
  assign _25_ = ~(transformer_overload | _24_);
  assign _26_ = ~(frequency_high | _25_);
  assign _27_ = ~(frequency_critical | _26_);
  assign _28_ = voltage_high | _27_;
  assign _29_ = ~(_22_ & _28_);
  assign _05_ = frequency_critical | solar_drop;
  assign _00_[0] = _17_ & _29_;
  assign _30_ = _18_ | ~(_19_);
  assign _31_ = ~(_21_ & _30_);
  assign _32_ = _22_ & _31_;
  assign _00_[1] = _17_ & _32_;
  assign _33_ = _23_ & ~(_20_);
  assign _00_[2] = _17_ & _33_;
  assign _06_ = ev_surge | _05_;
  assign _07_ = ~(_04_ & _06_);
  assign _08_ = ~(fault_injection_sig & _03_);
  assign _09_ = ~(transformer_overload & _02_);
  assign _10_ = ~(frequency_critical & solar_drop);
  assign _11_ = ~(voltage_high & voltage_low);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:37.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) fault_detected <= 1'h0;
    else fault_detected <= _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:37.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) fault_code[0] <= 1'h0;
    else fault_code[0] <= _00_[0];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:37.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) fault_code[1] <= 1'h0;
    else fault_code[1] <= _00_[1];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:37.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) fault_code[2] <= 1'h0;
    else fault_code[2] <= _00_[2];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/fault_detector.v:37.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) fault_code[3] <= 1'h0;
    else fault_code[3] <= _00_[3];
  assign fault_sum[3] = 1'h0;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:7.1-59.10" *)
module frequency_monitor(clk, reset, frequency, frequency_normal, frequency_warning, frequency_critical, frequency_high, frequency_severity);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:13.24-13.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:14.24-14.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:15.24-15.33" *)
  input [15:0] frequency;
  wire [15:0] frequency;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:16.24-16.40" *)
  output frequency_normal;
  reg frequency_normal;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:17.24-17.41" *)
  output frequency_warning;
  wire frequency_warning;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:18.24-18.42" *)
  output frequency_critical;
  wire frequency_critical;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:19.24-19.38" *)
  output frequency_high;
  reg frequency_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:20.24-20.42" *)
  output [1:0] frequency_severity;
  reg [1:0] frequency_severity;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  wire _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  wire _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  wire _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  wire [1:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  assign _04_ = ~(frequency[11] | frequency[10]);
  assign _05_ = frequency[8] & frequency[12];
  assign _14_ = frequency[5] & frequency[4];
  assign _15_ = frequency[3] & _14_;
  assign _16_ = frequency[1] & _15_;
  assign _17_ = frequency[0] | ~(_11_);
  assign _18_ = _08_ | _17_;
  assign _19_ = ~(_16_ & _18_);
  assign _20_ = _12_ | _16_;
  assign _21_ = frequency[2] & _15_;
  assign _22_ = ~(frequency[6] | _21_);
  assign _23_ = _20_ & _22_;
  assign _06_ = frequency[9] & _05_;
  assign _24_ = _19_ & _23_;
  assign _25_ = _13_ | _24_;
  assign _01_ = ~_25_;
  assign _26_ = frequency[3] | frequency[2];
  assign _27_ = frequency[6] & _14_;
  assign _28_ = _26_ & _27_;
  assign _29_ = frequency[7] | _28_;
  assign _30_ = ~(_06_ & _29_);
  assign _31_ = ~(_12_ & _30_);
  assign _02_ = _25_ & _31_;
  assign _07_ = _04_ & _06_;
  assign _32_ = frequency[1] | frequency[3];
  assign _33_ = frequency[4] & _26_;
  assign _34_ = _32_ & _33_;
  assign _35_ = frequency[5] | _34_;
  assign _36_ = frequency[6] & _07_;
  assign _37_ = ~(_35_ & _36_);
  assign _00_ = _13_ & _37_;
  assign _03_[0] = ~(_02_ | _00_);
  assign _08_ = ~(frequency[7] & _07_);
  assign _09_ = _04_ | ~(frequency[12]);
  assign _10_ = ~(frequency[15] | frequency[14]);
  assign _11_ = _10_ & ~(frequency[13]);
  assign _12_ = _09_ & _11_;
  assign _13_ = _08_ & _12_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) frequency_normal <= 1'h1;
    else frequency_normal <= _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) frequency_high <= 1'h0;
    else frequency_high <= _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) frequency_severity[0] <= 1'h0;
    else frequency_severity[0] <= _03_[0];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/frequency_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) frequency_severity[1] <= 1'h0;
    else frequency_severity[1] <= _00_;
  assign _03_[1] = _00_;
  assign frequency_critical = frequency_severity[1];
  assign frequency_warning = frequency_severity[0];
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:8.1-73.10" *)
module grid_stress_index(clk, reset, voltage_severity, frequency_severity, transformer_loading_percent, total_grid_load, ev_surge, solar_drop, battery_available, gsi);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:9.24-9.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:10.24-10.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:11.24-11.40" *)
  input [1:0] voltage_severity;
  wire [1:0] voltage_severity;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:12.24-12.42" *)
  input [1:0] frequency_severity;
  wire [1:0] frequency_severity;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:13.24-13.51" *)
  input [15:0] transformer_loading_percent;
  wire [15:0] transformer_loading_percent;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:14.24-14.39" *)
  input [15:0] total_grid_load;
  wire [15:0] total_grid_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:15.24-15.32" *)
  input ev_surge;
  wire ev_surge;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:16.24-16.34" *)
  input solar_drop;
  wire solar_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:17.24-17.41" *)
  input battery_available;
  wire battery_available;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:18.24-18.27" *)
  output [7:0] gsi;
  wire [7:0] gsi;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  assign _313_ = ~(total_grid_load[4] | total_grid_load[5]);
  assign _314_ = total_grid_load[6] | ~(_313_);
  assign _323_ = total_grid_load[11] & _322_;
  assign _050_ = _023_ & _046_;
  assign _051_ = _023_ ^ _046_;
  assign _052_ = ~(total_grid_load[4] & _051_);
  assign _053_ = _022_ ^ _047_;
  assign _054_ = ~(_024_ ^ _050_);
  assign _055_ = _053_ & _054_;
  assign _056_ = ~(_052_ & _055_);
  assign _057_ = _027_ & _046_;
  assign _058_ = _031_ & _057_;
  assign _059_ = ~(_031_ ^ _057_);
  assign _324_ = ~(_321_ & _323_);
  assign _060_ = _049_ & ~(_059_);
  assign _061_ = ~(_056_ & _060_);
  assign _062_ = ~(_030_ ^ _058_);
  assign _063_ = ~(_061_ & _062_);
  assign _064_ = _033_ & _046_;
  assign _065_ = ~(_034_ ^ _064_);
  assign _066_ = ~(_063_ & _065_);
  assign _067_ = _035_ & _046_;
  assign _068_ = ~(_037_ ^ _067_);
  assign _069_ = ~(_066_ & _068_);
  assign _325_ = ~(total_grid_load[15] | total_grid_load[14]);
  assign _070_ = _046_ | ~(_042_);
  assign _071_ = _045_ | ~(_038_);
  assign _072_ = _070_ & _071_;
  assign _073_ = ~(_069_ & _072_);
  assign _074_ = _056_ & _073_;
  assign _075_ = _049_ & _074_;
  assign _076_ = ~(_049_ ^ _074_);
  assign _077_ = _052_ & _073_;
  assign _078_ = _054_ & _077_;
  assign _079_ = ~(_053_ ^ _078_);
  assign _326_ = _324_ & _325_;
  assign _080_ = total_grid_load[4] & _073_;
  assign _081_ = total_grid_load[4] ^ _073_;
  assign _082_ = total_grid_load[3] | ~(_081_);
  assign _083_ = ~(_051_ ^ _080_);
  assign _084_ = ~(_054_ ^ _077_);
  assign _085_ = _083_ & ~(_084_);
  assign _086_ = ~(_082_ & _085_);
  assign _087_ = ~(_059_ ^ _075_);
  assign _088_ = _079_ & ~(_076_);
  assign _089_ = ~(_086_ & _088_);
  assign _327_ = total_grid_load[7] | _314_;
  assign _090_ = _087_ | ~(_089_);
  assign _091_ = _061_ & _073_;
  assign _092_ = _063_ & _073_;
  assign _093_ = ~(_062_ ^ _091_);
  assign _094_ = ~(_090_ & _093_);
  assign _095_ = ~(_065_ ^ _092_);
  assign _096_ = ~(_094_ & _095_);
  assign _097_ = _072_ ? _068_ : _066_;
  assign _098_ = ~(_069_ & _097_);
  assign _099_ = ~(_096_ & _098_);
  assign _328_ = total_grid_load[8] & _327_;
  assign _100_ = _086_ & _099_;
  assign _101_ = _079_ & _100_;
  assign _102_ = ~(_076_ ^ _101_);
  assign _103_ = total_grid_load[3] | ~(_099_);
  assign _104_ = _081_ ^ _103_;
  assign _105_ = total_grid_load[3] ^ _099_;
  assign _106_ = total_grid_load[2] | _105_;
  assign _107_ = _082_ & _099_;
  assign _108_ = _083_ & _107_;
  assign _109_ = _083_ ^ _107_;
  assign _329_ = total_grid_load[9] & _328_;
  assign _110_ = _106_ & _109_;
  assign _111_ = ~(_104_ & _110_);
  assign _112_ = ~(_084_ ^ _108_);
  assign _113_ = ~(_079_ ^ _100_);
  assign _114_ = ~(_112_ | _113_);
  assign _115_ = _111_ & _114_;
  assign _116_ = _089_ & _099_;
  assign _117_ = _090_ & _099_;
  assign _118_ = ~(_087_ ^ _116_);
  assign _119_ = _102_ | _115_;
  assign _330_ = total_grid_load[10] & _329_;
  assign _120_ = _118_ | ~(_119_);
  assign _121_ = ~(_093_ ^ _117_);
  assign _122_ = ~(_120_ & _121_);
  assign _123_ = _098_ ? _095_ : _094_;
  assign _124_ = ~(_096_ & _123_);
  assign _125_ = ~(_122_ & _124_);
  assign _126_ = _115_ | ~(_125_);
  assign _127_ = ~(_119_ & _125_);
  assign _128_ = _102_ ^ _126_;
  assign _129_ = _111_ & _125_;
  assign _331_ = total_grid_load[11] | _330_;
  assign _130_ = _129_ & ~(_112_);
  assign _131_ = ~(_113_ ^ _130_);
  assign _132_ = _120_ | _124_;
  assign _133_ = ~(_118_ ^ _127_);
  assign _134_ = total_grid_load[2] | ~(_125_);
  assign _135_ = total_grid_load[2] ^ _125_;
  assign _136_ = ~(total_grid_load[1] | _135_);
  assign _137_ = ~(_105_ & _136_);
  assign _138_ = _105_ ^ _134_;
  assign _139_ = _136_ | _138_;
  assign _332_ = total_grid_load[12] | _331_;
  assign _140_ = _106_ & _125_;
  assign _141_ = _104_ & _140_;
  assign _142_ = ~(_104_ ^ _140_);
  assign _143_ = total_grid_load[0] & total_grid_load[1];
  assign _144_ = ~(_135_ & _143_);
  assign _145_ = _142_ & _144_;
  assign _146_ = _139_ & _145_;
  assign _147_ = ~(_137_ & _146_);
  assign _148_ = ~(_112_ ^ _129_);
  assign _149_ = ~(_109_ ^ _141_);
  assign _315_ = total_grid_load[7] & _314_;
  assign _333_ = total_grid_load[13] & _332_;
  assign _150_ = ~(_148_ | _149_);
  assign _151_ = ~(_147_ & _150_);
  assign _152_ = _133_ & _151_;
  assign _153_ = _131_ | _152_;
  assign _154_ = total_grid_load[0] | total_grid_load[1];
  assign _155_ = ~(_135_ & _154_);
  assign _156_ = _138_ | _155_;
  assign _157_ = _142_ & _149_;
  assign _158_ = ~(_156_ & _157_);
  assign _159_ = ~(_133_ | _148_);
  assign _334_ = total_grid_load[14] | _333_;
  assign _160_ = ~(_158_ & _159_);
  assign _161_ = ~(_153_ & _160_);
  assign _162_ = ~(_128_ & _161_);
  assign _163_ = _121_ ? _120_ : _124_;
  assign _164_ = _163_ | ~(_132_);
  assign _165_ = _139_ | _142_;
  assign _166_ = _148_ & _149_;
  assign _167_ = _165_ & _166_;
  assign _168_ = ~(_131_ | _167_);
  assign _169_ = _128_ | _168_;
  assign _335_ = _333_ | ~(_325_);
  assign _170_ = _169_ | ~(_133_);
  assign _171_ = _164_ & _170_;
  assign _172_ = ~(_133_ & _169_);
  assign _173_ = ~(_164_ & _172_);
  assign _174_ = ~(_162_ & _171_);
  assign _175_ = ~(_335_ & _174_);
  assign _176_ = ~(_326_ & _175_);
  assign _177_ = voltage_severity[1] & ~(voltage_severity[0]);
  assign _178_ = voltage_severity[0] & ~(voltage_severity[1]);
  assign _179_ = ~(_177_ | _178_);
  assign _336_ = total_grid_load[7] ^ _314_;
  assign _180_ = _177_ | _178_;
  assign _181_ = transformer_loading_percent[5] & transformer_loading_percent[6];
  assign _182_ = transformer_loading_percent[2] | transformer_loading_percent[3];
  assign _183_ = transformer_loading_percent[4] | _182_;
  assign _184_ = ~(_181_ & _183_);
  assign _185_ = ~(transformer_loading_percent[12] | transformer_loading_percent[14]);
  assign _186_ = _185_ & ~(transformer_loading_percent[7]);
  assign _187_ = ~(transformer_loading_percent[15] | transformer_loading_percent[9]);
  assign _188_ = ~(transformer_loading_percent[8] | transformer_loading_percent[11]);
  assign _189_ = ~(transformer_loading_percent[10] | transformer_loading_percent[13]);
  assign _337_ = total_grid_load[15] ^ _334_;
  assign _190_ = _188_ & _189_;
  assign _191_ = _187_ & _190_;
  assign _192_ = _186_ & _191_;
  assign _193_ = _184_ & _192_;
  assign _194_ = transformer_loading_percent[5] | transformer_loading_percent[4];
  assign _195_ = transformer_loading_percent[6] & _194_;
  assign _196_ = transformer_loading_percent[0] & _193_;
  assign _197_ = _195_ & _196_;
  assign _198_ = ~(_180_ & _197_);
  assign _199_ = ~(_179_ ^ _197_);
  assign _338_ = ~(total_grid_load[14] ^ _333_);
  assign _200_ = ~(_176_ & _199_);
  assign _201_ = _176_ ^ _199_;
  assign _202_ = ~(_333_ & _173_);
  assign _203_ = ~(_326_ & _202_);
  assign _204_ = transformer_loading_percent[1] & _193_;
  assign _205_ = _195_ & _204_;
  assign _206_ = ~(_203_ & _205_);
  assign _207_ = _203_ ^ _205_;
  assign _208_ = ~(_198_ & _200_);
  assign _209_ = ~(solar_drop & ev_surge);
  assign _339_ = total_grid_load[13] ^ _332_;
  assign _210_ = solar_drop ^ ev_surge;
  assign _211_ = ~(_178_ & _210_);
  assign _212_ = _178_ ^ _210_;
  assign _213_ = ~(_208_ & _212_);
  assign _214_ = _208_ ^ _212_;
  assign _215_ = ~(_207_ & _214_);
  assign _216_ = _207_ ^ _214_;
  assign _217_ = ~(_209_ & _211_);
  assign _218_ = ~(transformer_loading_percent[2] & _195_);
  assign _219_ = ~(_193_ & _218_);
  assign _340_ = ~(total_grid_load[10] ^ _329_);
  assign _220_ = frequency_severity[1] & ~(frequency_severity[0]);
  assign _221_ = frequency_severity[0] & ~(frequency_severity[1]);
  assign _222_ = _220_ | _221_;
  assign _223_ = ~(_178_ & _222_);
  assign _224_ = _178_ ^ _222_;
  assign _225_ = ~(_219_ & _224_);
  assign _226_ = _219_ ^ _224_;
  assign _227_ = ~(_217_ & _226_);
  assign _228_ = ~(_333_ & _125_);
  assign _229_ = ~(_326_ & _228_);
  assign _341_ = ~(total_grid_load[9] ^ _328_);
  assign _230_ = _217_ ^ _226_;
  assign _231_ = ~(_229_ & _230_);
  assign _232_ = ~(_227_ & _231_);
  assign _233_ = ~(_333_ & _099_);
  assign _234_ = ~(_326_ & _233_);
  assign _235_ = transformer_loading_percent[3] & _193_;
  assign _236_ = _195_ & _235_;
  assign _237_ = ~(_221_ & _236_);
  assign _238_ = _221_ ^ _236_;
  assign _239_ = ~(_234_ & _238_);
  assign _342_ = ~(total_grid_load[8] & _336_);
  assign _240_ = _234_ ^ _238_;
  assign _241_ = ~(_223_ & _225_);
  assign _242_ = ~(_180_ & _210_);
  assign _243_ = ~(_179_ ^ _210_);
  assign _244_ = ~(_241_ & _243_);
  assign _245_ = _241_ ^ _243_;
  assign _246_ = ~(_240_ & _245_);
  assign _247_ = _240_ ^ _245_;
  assign _248_ = _232_ & _247_;
  assign _249_ = ~(_237_ & _239_);
  assign _316_ = total_grid_load[3] | total_grid_load[6];
  assign _343_ = _341_ | ~(_342_);
  assign _250_ = ~(_244_ & _246_);
  assign _251_ = ~(_209_ & _242_);
  assign _252_ = _181_ | ~(_192_);
  assign _253_ = ~(_177_ & _220_);
  assign _254_ = _177_ ^ _220_;
  assign _255_ = ~(_252_ & _254_);
  assign _256_ = _252_ ^ _254_;
  assign _257_ = ~(_251_ & _256_);
  assign _258_ = _251_ ^ _256_;
  assign _259_ = ~(_250_ & _258_);
  assign _344_ = _340_ | _343_;
  assign _260_ = _250_ ^ _258_;
  assign _261_ = ~(_249_ & _260_);
  assign _262_ = _249_ ^ _260_;
  assign _263_ = ~(_248_ & _262_);
  assign _264_ = ~(_213_ & _215_);
  assign _265_ = _229_ ^ _230_;
  assign _266_ = ~(_264_ & _265_);
  assign _267_ = _264_ ^ _265_;
  assign _268_ = _206_ | ~(_267_);
  assign _269_ = ~(_266_ & _268_);
  assign _345_ = ~(total_grid_load[11] ^ _330_);
  assign _270_ = _232_ ^ _247_;
  assign _271_ = _269_ & _270_;
  assign _272_ = _248_ ^ _262_;
  assign _273_ = ~(_271_ & _272_);
  assign _274_ = _263_ & _273_;
  assign _275_ = ~(_259_ & _261_);
  assign _276_ = _253_ | _257_;
  assign _277_ = ~(_253_ & _255_);
  assign _278_ = _257_ ? _277_ : _253_;
  assign _279_ = ~(_275_ & _278_);
  assign _346_ = _345_ | ~(_344_);
  assign _280_ = ~(_275_ ^ _278_);
  assign _281_ = _274_ | _280_;
  assign _282_ = _276_ & _279_;
  assign _283_ = _281_ & _282_;
  assign _284_ = _271_ ^ _272_;
  assign _285_ = _269_ ^ _270_;
  assign _286_ = ~(_206_ ^ _267_);
  assign _287_ = _206_ ^ _267_;
  assign _288_ = ~(_201_ & _216_);
  assign _289_ = ~(_287_ & _288_);
  assign _347_ = total_grid_load[12] | _346_;
  assign _290_ = _285_ & _289_;
  assign _291_ = ~(_284_ | _290_);
  assign _292_ = _274_ & _280_;
  assign _293_ = _291_ & _292_;
  assign _294_ = _283_ & _293_;
  assign _295_ = ~(battery_available | _294_);
  assign _296_ = _216_ & _295_;
  assign _297_ = _216_ ^ _295_;
  assign _298_ = _201_ | _297_;
  assign _299_ = ~(_287_ ^ _296_);
  assign _348_ = ~(_339_ & _347_);
  assign _300_ = ~(_298_ & _299_);
  assign _301_ = ~(_216_ & _286_);
  assign _302_ = _285_ | ~(_301_);
  assign _303_ = _295_ & _302_;
  assign _304_ = _284_ & _303_;
  assign _000_[4] = _284_ ^ _303_;
  assign _305_ = _295_ & _301_;
  assign _306_ = ~(_285_ ^ _305_);
  assign _307_ = _306_ & ~(_000_[4]);
  assign _308_ = ~(_300_ & _307_);
  assign _349_ = _348_ & ~(_338_);
  assign _309_ = _281_ & ~(_292_);
  assign _310_ = ~(_304_ & _309_);
  assign _000_[5] = _304_ ^ _309_;
  assign _311_ = _000_[5] & ~(_283_);
  assign _312_ = ~(_308_ & _311_);
  assign _000_[0] = _201_ & _312_;
  assign _000_[1] = _297_ & _312_;
  assign _000_[2] = _299_ | ~(_312_);
  assign _000_[3] = ~(_306_ | _311_);
  assign _000_[6] = ~(_283_ & _310_);
  assign _350_ = ~(_337_ | _349_);
  assign _351_ = ~(_336_ & _350_);
  assign _352_ = _327_ & _351_;
  assign _317_ = total_grid_load[5] | _316_;
  assign _353_ = ~(total_grid_load[8] ^ _352_);
  assign _354_ = ~(total_grid_load[6] ^ _313_);
  assign _355_ = _336_ ^ _350_;
  assign _356_ = ~(_354_ & _355_);
  assign _357_ = _337_ | ~(_349_);
  assign _358_ = ~(_348_ & _350_);
  assign _359_ = _338_ & _358_;
  assign _360_ = _342_ & _350_;
  assign _361_ = _343_ | ~(_350_);
  assign _362_ = ~(_341_ ^ _360_);
  assign _318_ = _315_ & _317_;
  assign _363_ = ~(_356_ & _362_);
  assign _001_ = _353_ | _363_;
  assign _002_ = _344_ & _350_;
  assign _003_ = _346_ | ~(_350_);
  assign _004_ = ~(_345_ ^ _002_);
  assign _005_ = _340_ ^ _361_;
  assign _006_ = _004_ & ~(_005_);
  assign _007_ = ~(_001_ & _006_);
  assign _008_ = _331_ & _003_;
  assign _009_ = ~(total_grid_load[12] ^ _008_);
  assign _319_ = total_grid_load[8] | _318_;
  assign _010_ = ~(_007_ & _009_);
  assign _011_ = _339_ | _347_;
  assign _012_ = _350_ ? _348_ : _339_;
  assign _013_ = ~(_011_ & _012_);
  assign _014_ = _010_ & _013_;
  assign _015_ = ~(_010_ & _013_);
  assign _016_ = ~(_359_ & _015_);
  assign _017_ = ~(_357_ & _016_);
  assign _018_ = ~(_356_ & _017_);
  assign _019_ = ~(_353_ | _018_);
  assign _320_ = total_grid_load[9] & _319_;
  assign _020_ = _353_ ^ _018_;
  assign _021_ = ~(_354_ & _017_);
  assign _022_ = ~(_355_ ^ _021_);
  assign _023_ = total_grid_load[4] ^ total_grid_load[5];
  assign _024_ = _354_ ^ _017_;
  assign _025_ = ~(_023_ & _024_);
  assign _026_ = ~(_020_ & _025_);
  assign _027_ = _022_ | _026_;
  assign _028_ = _001_ & _017_;
  assign _029_ = _028_ & ~(_005_);
  assign _321_ = total_grid_load[10] | _320_;
  assign _030_ = ~(_005_ ^ _028_);
  assign _031_ = ~(_362_ ^ _019_);
  assign _032_ = _030_ & _031_;
  assign _033_ = ~(_027_ & _032_);
  assign _034_ = ~(_004_ ^ _029_);
  assign _035_ = ~(_033_ & _034_);
  assign _036_ = _007_ & _017_;
  assign _037_ = ~(_009_ ^ _036_);
  assign _038_ = ~(_035_ & _037_);
  assign _039_ = _357_ | _015_;
  assign _322_ = total_grid_load[13] & total_grid_load[12];
  assign _040_ = _010_ & _017_;
  assign _041_ = _013_ | _040_;
  assign _042_ = ~(_039_ & _041_);
  assign _043_ = ~(_038_ & _042_);
  assign _044_ = ~(_359_ & _014_);
  assign _045_ = _357_ ? _044_ : _014_;
  assign _046_ = ~(_043_ & _045_);
  assign _047_ = ~(_025_ & _046_);
  assign _048_ = ~(_022_ | _047_);
  assign _049_ = ~(_020_ ^ _048_);
  reg \gsi_reg[0] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \gsi_reg[0]  <= 1'h0;
    else \gsi_reg[0]  <= _000_[0];
  assign gsi[0] = \gsi_reg[0] ;
  reg \gsi_reg[1] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \gsi_reg[1]  <= 1'h0;
    else \gsi_reg[1]  <= _000_[1];
  assign gsi[1] = \gsi_reg[1] ;
  reg \gsi_reg[2] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \gsi_reg[2]  <= 1'h0;
    else \gsi_reg[2]  <= _000_[2];
  assign gsi[2] = \gsi_reg[2] ;
  reg \gsi_reg[3] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \gsi_reg[3]  <= 1'h0;
    else \gsi_reg[3]  <= _000_[3];
  assign gsi[3] = \gsi_reg[3] ;
  reg \gsi_reg[4] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \gsi_reg[4]  <= 1'h0;
    else \gsi_reg[4]  <= _000_[4];
  assign gsi[4] = \gsi_reg[4] ;
  reg \gsi_reg[5] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \gsi_reg[5]  <= 1'h0;
    else \gsi_reg[5]  <= _000_[5];
  assign gsi[5] = \gsi_reg[5] ;
  reg \gsi_reg[6] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/grid_stress_index.v:29.5-71.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \gsi_reg[6]  <= 1'h0;
    else \gsi_reg[6]  <= _000_[6];
  assign gsi[6] = \gsi_reg[6] ;
  assign _000_[7] = 1'h0;
  assign gsi[7] = 1'h0;
endmodule

(* top =  1  *)
(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:6.1-168.10" *)
module gridguard_top(clock, reset, voltage, current, active_power, reactive_power, frequency, transformer_loading_percent, solar_generation, ev_charging_load, battery_soc, total_grid_load, fault_injection_sig, voltage_status, frequency_status, overload_status, solar_drop_status, ev_surge_status, battery_status, fault_detected, fault_code
, grid_stress_index, blackout_risk_indicator, warning_alarm, critical_alarm, emergency_alarm, reduce_ev_load, activate_battery_support, reduce_noncritical_load, preserve_critical_load);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:7.24-7.29" *)
  input clock;
  wire clock;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:8.24-8.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:11.24-11.31" *)
  input [15:0] voltage;
  wire [15:0] voltage;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:12.24-12.31" *)
  input [15:0] current;
  wire [15:0] current;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:13.24-13.36" *)
  input [15:0] active_power;
  wire [15:0] active_power;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:14.24-14.38" *)
  input [15:0] reactive_power;
  wire [15:0] reactive_power;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:15.24-15.33" *)
  input [15:0] frequency;
  wire [15:0] frequency;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:16.24-16.51" *)
  input [15:0] transformer_loading_percent;
  wire [15:0] transformer_loading_percent;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:17.24-17.40" *)
  input [15:0] solar_generation;
  wire [15:0] solar_generation;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:18.24-18.40" *)
  input [15:0] ev_charging_load;
  wire [15:0] ev_charging_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:19.24-19.35" *)
  input [15:0] battery_soc;
  wire [15:0] battery_soc;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:20.24-20.39" *)
  input [15:0] total_grid_load;
  wire [15:0] total_grid_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:21.24-21.43" *)
  input fault_injection_sig;
  wire fault_injection_sig;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:24.24-24.38" *)
  output [1:0] voltage_status;
  wire [1:0] voltage_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:25.24-25.40" *)
  output [1:0] frequency_status;
  wire [1:0] frequency_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:26.24-26.39" *)
  output overload_status;
  wire overload_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:27.24-27.41" *)
  output solar_drop_status;
  wire solar_drop_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:28.24-28.39" *)
  output ev_surge_status;
  wire ev_surge_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:29.24-29.38" *)
  output battery_status;
  wire battery_status;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:30.24-30.38" *)
  output fault_detected;
  wire fault_detected;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:31.24-31.34" *)
  output [3:0] fault_code;
  wire [3:0] fault_code;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:32.24-32.41" *)
  output [7:0] grid_stress_index;
  wire [7:0] grid_stress_index;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:33.24-33.47" *)
  output [7:0] blackout_risk_indicator;
  wire [7:0] blackout_risk_indicator;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:34.24-34.37" *)
  output warning_alarm;
  wire warning_alarm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:35.24-35.38" *)
  output critical_alarm;
  wire critical_alarm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:36.24-36.39" *)
  output emergency_alarm;
  wire emergency_alarm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:39.24-39.38" *)
  output reduce_ev_load;
  wire reduce_ev_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:40.24-40.48" *)
  output activate_battery_support;
  wire activate_battery_support;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:41.24-41.47" *)
  output reduce_noncritical_load;
  wire reduce_noncritical_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:42.24-42.46" *)
  output preserve_critical_load;
  wire preserve_critical_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:53.10-53.17" *)
  wire b_avail;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:53.26-53.32" *)
  wire b_crit;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:53.19-53.24" *)
  wire b_low;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:53.34-53.41" *)
  wire b_ready;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:52.19-52.26" *)
  wire ev_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:52.10-52.17" *)
  wire ev_norm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:52.28-52.41" *)
  wire ev_surge_flag;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:47.26-47.32" *)
  wire f_crit;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:47.34-47.40" *)
  wire f_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:47.10-47.16" *)
  wire f_norm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:47.18-47.24" *)
  wire f_warn;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:54.10-54.21" *)
  wire prot_active;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:51.26-51.37" *)
  wire s_crit_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:51.18-51.24" *)
  wire s_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:51.10-51.16" *)
  wire s_norm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:50.26-50.32" *)
  wire t_crit;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:50.10-50.16" *)
  wire t_norm;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:50.34-50.44" *)
  wire t_overload;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:50.18-50.24" *)
  wire t_warn;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:46.33-46.39" *)
  wire v_crit;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:46.25-46.31" *)
  wire v_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:46.18-46.23" *)
  wire v_low;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:46.10-46.16" *)
  wire v_norm;
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:156.22-160.6" *)
  alarm_controller inst_alarm (
    .blackout_risk_indicator(blackout_risk_indicator),
    .clk(clock),
    .critical_alarm(critical_alarm),
    .emergency_alarm(emergency_alarm),
    .fault_detected(fault_detected),
    .gsi(grid_stress_index),
    .reset(reset),
    .warning_alarm(warning_alarm)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:102.21-106.6" *)
  battery_monitor inst_b_mon (
    .battery_available(b_avail),
    .battery_critical(b_crit),
    .battery_low(b_low),
    .battery_ready_for_support(b_ready),
    .battery_soc(battery_soc),
    .clk(clock),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:148.30-153.6" *)
  critical_load_protection inst_crit_prot (
    .clk(clock),
    .gsi(grid_stress_index),
    .preserve_critical_load(preserve_critical_load),
    .reduce_noncritical_load(reduce_noncritical_load),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:96.21-99.6" *)
  ev_load_monitor inst_ev_mon (
    .clk(clock),
    .ev_charging_load(ev_charging_load),
    .ev_high(ev_high),
    .ev_normal(ev_norm),
    .ev_surge(ev_surge_flag),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:64.23-68.6" *)
  frequency_monitor inst_f_mon (
    .clk(clock),
    .frequency(frequency),
    .frequency_critical(f_crit),
    .frequency_high(f_high),
    .frequency_normal(f_norm),
    .frequency_severity(frequency_status),
    .frequency_warning(f_warn),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:109.20-116.6" *)
  fault_detector inst_fault_det (
    .clk(clock),
    .ev_surge(ev_surge_flag),
    .fault_code(fault_code),
    .fault_detected(fault_detected),
    .fault_injection_sig(fault_injection_sig),
    .frequency_critical(f_crit),
    .frequency_high(f_high),
    .reset(reset),
    .solar_drop(s_drop),
    .transformer_overload(t_overload),
    .voltage_high(v_high),
    .voltage_low(v_low)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:119.23-126.6" *)
  grid_stress_index inst_gsi (
    .battery_available(b_avail),
    .clk(clock),
    .ev_surge(ev_surge_flag),
    .frequency_severity(frequency_status),
    .gsi(grid_stress_index),
    .reset(reset),
    .solar_drop(s_drop),
    .total_grid_load(total_grid_load),
    .transformer_loading_percent(transformer_loading_percent),
    .voltage_severity(voltage_status)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:137.27-145.6" *)
  protection_controller inst_prot (
    .activate_battery_support(activate_battery_support),
    .battery_available(b_avail),
    .clk(clock),
    .ev_surge(ev_surge_flag),
    .gsi(grid_stress_index),
    .protection_action_active(prot_active),
    .reduce_ev_load(reduce_ev_load),
    .reduce_noncritical_load(reduce_noncritical_load),
    .reset(reset),
    .solar_drop(s_drop),
    .transformer_overload(t_overload)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:129.19-134.6" *)
  blackout_risk inst_risk (
    .battery_available(b_avail),
    .blackout_risk_indicator(blackout_risk_indicator),
    .clk(clock),
    .ev_surge(ev_surge_flag),
    .frequency_critical(f_crit),
    .gsi(grid_stress_index),
    .reset(reset),
    .solar_drop(s_drop),
    .transformer_overload(t_overload),
    .voltage_critical(v_crit)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:90.19-93.6" *)
  solar_monitor inst_s_mon (
    .clk(clock),
    .reset(reset),
    .solar_critical_drop(s_crit_drop),
    .solar_drop(s_drop),
    .solar_generation(solar_generation),
    .solar_normal(s_norm)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:83.25-87.6" *)
  transformer_monitor inst_t_mon (
    .clk(clock),
    .reset(reset),
    .transformer_critical(t_crit),
    .transformer_loading_percent(transformer_loading_percent),
    .transformer_normal(t_norm),
    .transformer_overload(t_overload),
    .transformer_warning(t_warn)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/gridguard_top.v:57.21-61.6" *)
  voltage_monitor inst_v_mon (
    .clk(clock),
    .reset(reset),
    .voltage(voltage),
    .voltage_critical(v_crit),
    .voltage_high(v_high),
    .voltage_low(v_low),
    .voltage_normal(v_norm),
    .voltage_severity(voltage_status)
  );
  assign battery_status = b_avail;
  assign ev_surge_status = ev_surge_flag;
  assign solar_drop_status = s_drop;
  assign overload_status = t_overload;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:8.1-55.10" *)
module protection_controller(clk, reset, gsi, transformer_overload, ev_surge, solar_drop, battery_available, reduce_ev_load, activate_battery_support, reduce_noncritical_load, protection_action_active);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:9.24-9.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:10.24-10.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:11.24-11.27" *)
  input [7:0] gsi;
  wire [7:0] gsi;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:12.24-12.44" *)
  input transformer_overload;
  wire transformer_overload;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:13.24-13.32" *)
  input ev_surge;
  wire ev_surge;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:14.24-14.34" *)
  input solar_drop;
  wire solar_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:15.24-15.41" *)
  input battery_available;
  wire battery_available;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:16.24-16.38" *)
  output reduce_ev_load;
  reg reduce_ev_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:17.24-17.48" *)
  output activate_battery_support;
  reg activate_battery_support;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:18.24-18.47" *)
  output reduce_noncritical_load;
  reg reduce_noncritical_load;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:19.24-19.48" *)
  output protection_action_active;
  reg protection_action_active;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  wire _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  wire _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  wire _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  assign _04_ = ~(gsi[6] | gsi[7]);
  assign _05_ = gsi[1] | gsi[3];
  assign _01_ = reduce_noncritical_load | _12_;
  assign _13_ = ~(transformer_overload | ev_surge);
  assign _02_ = ~(_09_ & _13_);
  assign _14_ = gsi[1] & gsi[0];
  assign _15_ = gsi[2] | _14_;
  assign _16_ = ~(gsi[3] & _15_);
  assign _17_ = ~(gsi[5] | gsi[7]);
  assign _18_ = _17_ & ~(gsi[4]);
  assign _19_ = _16_ & _18_;
  assign _20_ = ~(_04_ | _19_);
  assign _06_ = gsi[2] | _05_;
  assign _03_ = transformer_overload | _20_;
  assign _07_ = gsi[4] & gsi[5];
  assign _08_ = ~(_06_ & _07_);
  assign _09_ = _04_ & _08_;
  assign _10_ = ~(transformer_overload | solar_drop);
  assign _11_ = ~(_09_ & _10_);
  assign _00_ = battery_available & _11_;
  assign _12_ = reduce_ev_load | activate_battery_support;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) reduce_ev_load <= 1'h0;
    else reduce_ev_load <= _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) activate_battery_support <= 1'h0;
    else activate_battery_support <= _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) reduce_noncritical_load <= 1'h0;
    else reduce_noncritical_load <= _03_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/protection_controller.v:22.5-53.8" *)
  always @(posedge clk, posedge reset)
    if (reset) protection_action_active <= 1'h0;
    else protection_action_active <= _01_;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:7.1-41.10" *)
module solar_monitor(clk, reset, solar_generation, solar_normal, solar_drop, solar_critical_drop);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:11.24-11.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:12.24-12.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:13.24-13.40" *)
  input [15:0] solar_generation;
  wire [15:0] solar_generation;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:14.24-14.36" *)
  output solar_normal;
  reg solar_normal;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:15.24-15.34" *)
  output solar_drop;
  reg solar_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:16.24-16.43" *)
  output solar_critical_drop;
  reg solar_critical_drop;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  wire _000_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  wire _001_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:19.16-19.30" *)
  reg [15:0] prev_solar_gen;
  assign _103_ = solar_generation[15] | ~(prev_solar_gen[15]);
  assign _104_ = prev_solar_gen[15] | ~(solar_generation[15]);
  assign _113_ = ~(prev_solar_gen[12] ^ solar_generation[12]);
  assign _039_ = _037_ & ~(_038_);
  assign _040_ = _036_ & ~(_032_);
  assign _041_ = _039_ & _040_;
  assign _042_ = ~(_106_ | _035_);
  assign _043_ = ~(_105_ ^ _042_);
  assign _044_ = _041_ & ~(_043_);
  assign _045_ = _120_ ^ _025_;
  assign _046_ = _126_ & _162_;
  assign _047_ = ~(_125_ | _046_);
  assign _048_ = ~(_124_ ^ _047_);
  assign _114_ = _111_ & _113_;
  assign _049_ = _134_ & _158_;
  assign _050_ = _133_ | _049_;
  assign _051_ = ~(_132_ ^ _050_);
  assign _052_ = ~(_134_ ^ _158_);
  assign _053_ = _156_ ^ _017_;
  assign _054_ = _052_ & _053_;
  assign _055_ = ~(_051_ & _054_);
  assign _056_ = _126_ ^ _162_;
  assign _057_ = _055_ & _056_;
  assign _058_ = ~(_048_ & _057_);
  assign _115_ = _108_ & _114_;
  assign _059_ = _045_ & _058_;
  assign _060_ = ~(_044_ & _059_);
  assign _061_ = ~(_023_ & _060_);
  assign _062_ = ~(solar_generation[12] | solar_generation[11]);
  assign _063_ = _062_ & ~(solar_generation[15]);
  assign _064_ = ~(solar_generation[14] | solar_generation[13]);
  assign _065_ = _063_ & _064_;
  assign _066_ = _065_ & ~(solar_generation[10]);
  assign _067_ = solar_generation[4] | solar_generation[3];
  assign _068_ = solar_generation[8] & solar_generation[7];
  assign _116_ = solar_generation[11] | ~(prev_solar_gen[11]);
  assign _069_ = solar_generation[9] & solar_generation[6];
  assign _070_ = solar_generation[5] & ~(solar_generation[10]);
  assign _071_ = _069_ & _070_;
  assign _072_ = _068_ & _071_;
  assign _073_ = ~(_067_ & _072_);
  assign _074_ = ~(_066_ & _073_);
  assign _075_ = ~(solar_generation[4] | solar_generation[2]);
  assign _076_ = ~(solar_generation[1] | solar_generation[0]);
  assign _077_ = _075_ & _076_;
  assign _078_ = solar_generation[3] & _077_;
  assign _117_ = solar_generation[11] & ~(prev_solar_gen[11]);
  assign _079_ = _065_ & _078_;
  assign _080_ = ~(_072_ & _079_);
  assign _081_ = _074_ & _080_;
  assign _002_ = _061_ & _081_;
  assign _001_ = ~(_061_ & _081_);
  assign _082_ = _077_ & ~(solar_generation[3]);
  assign _083_ = _082_ | ~(solar_generation[5]);
  assign _084_ = ~(solar_generation[7] | solar_generation[6]);
  assign _085_ = ~(_083_ & _084_);
  assign _086_ = solar_generation[9] & solar_generation[8];
  assign _118_ = _116_ & ~(_117_);
  assign _087_ = ~(_085_ & _086_);
  assign _088_ = ~(_066_ & _087_);
  assign _089_ = _139_ | _154_;
  assign _090_ = _141_ ^ _142_;
  assign _091_ = _143_ ^ _150_;
  assign _092_ = _089_ & _091_;
  assign _093_ = _090_ & _092_;
  assign _094_ = ~(_155_ & _093_);
  assign _095_ = ~(_053_ & _094_);
  assign _096_ = _095_ & ~(_052_);
  assign _119_ = solar_generation[10] | ~(prev_solar_gen[10]);
  assign _097_ = ~(_056_ & _096_);
  assign _098_ = _051_ | _097_;
  assign _099_ = _098_ & ~(_048_);
  assign _100_ = _045_ | _099_;
  assign _101_ = ~(_044_ & _100_);
  assign _102_ = ~(_023_ & _101_);
  assign _000_ = ~(_088_ & _102_);
  assign _120_ = ~(prev_solar_gen[10] ^ solar_generation[10]);
  assign _121_ = _118_ & _120_;
  assign _122_ = solar_generation[9] | ~(prev_solar_gen[9]);
  assign _105_ = _103_ & _104_;
  assign _123_ = prev_solar_gen[9] | ~(solar_generation[9]);
  assign _124_ = _122_ & _123_;
  assign _125_ = prev_solar_gen[8] & ~(solar_generation[8]);
  assign _126_ = ~(prev_solar_gen[8] ^ solar_generation[8]);
  assign _127_ = _124_ & _126_;
  assign _128_ = _121_ & _127_;
  assign _129_ = _115_ & _128_;
  assign _130_ = solar_generation[7] | ~(prev_solar_gen[7]);
  assign _131_ = prev_solar_gen[7] | ~(solar_generation[7]);
  assign _132_ = _130_ & _131_;
  assign _106_ = prev_solar_gen[14] & ~(solar_generation[14]);
  assign _133_ = prev_solar_gen[6] & ~(solar_generation[6]);
  assign _134_ = ~(prev_solar_gen[6] ^ solar_generation[6]);
  assign _135_ = _132_ & _134_;
  assign _136_ = prev_solar_gen[5] | ~(solar_generation[5]);
  assign _137_ = solar_generation[5] | ~(prev_solar_gen[5]);
  assign _138_ = solar_generation[4] | ~(prev_solar_gen[4]);
  assign _139_ = ~(prev_solar_gen[4] ^ solar_generation[4]);
  assign _140_ = solar_generation[3] | ~(prev_solar_gen[3]);
  assign _141_ = ~(prev_solar_gen[3] ^ solar_generation[3]);
  assign _142_ = prev_solar_gen[2] & ~(solar_generation[2]);
  assign _107_ = ~(prev_solar_gen[14] ^ solar_generation[14]);
  assign _143_ = ~(prev_solar_gen[2] ^ solar_generation[2]);
  assign _144_ = _141_ & _143_;
  assign _145_ = solar_generation[1] | ~(prev_solar_gen[1]);
  assign _146_ = prev_solar_gen[0] | ~(solar_generation[0]);
  assign _147_ = prev_solar_gen[1] | ~(solar_generation[1]);
  assign _148_ = ~(_146_ & _147_);
  assign _149_ = _145_ & ~(_148_);
  assign _150_ = ~(_145_ & _148_);
  assign _151_ = ~(_144_ & _150_);
  assign _152_ = ~(_141_ & _142_);
  assign _108_ = _105_ & _107_;
  assign _153_ = _140_ & _152_;
  assign _154_ = ~(_151_ & _153_);
  assign _155_ = ~(_139_ & _154_);
  assign _156_ = _138_ & _155_;
  assign _157_ = ~(_137_ & _156_);
  assign _158_ = _136_ & _157_;
  assign _159_ = ~(_135_ & _158_);
  assign _160_ = ~(_131_ & _133_);
  assign _161_ = _130_ & _160_;
  assign _162_ = ~(_159_ & _161_);
  assign _109_ = solar_generation[13] | ~(prev_solar_gen[13]);
  assign _163_ = ~(_129_ & _162_);
  assign _164_ = ~(_123_ & _125_);
  assign _165_ = _122_ & _164_;
  assign _166_ = _165_ | ~(_121_);
  assign _003_ = _117_ | _119_;
  assign _004_ = _116_ & _003_;
  assign _005_ = _166_ & _004_;
  assign _006_ = _005_ | ~(_115_);
  assign _007_ = ~(_110_ & _112_);
  assign _008_ = _109_ & _007_;
  assign _110_ = prev_solar_gen[13] | ~(solar_generation[13]);
  assign _009_ = _008_ | ~(_108_);
  assign _010_ = ~(_104_ & _106_);
  assign _011_ = _103_ & _010_;
  assign _012_ = _009_ & _011_;
  assign _013_ = _006_ & _012_;
  assign _014_ = ~(_163_ & _013_);
  assign _015_ = _135_ & _144_;
  assign _016_ = solar_generation[0] | ~(prev_solar_gen[0]);
  assign _017_ = _136_ & _137_;
  assign _018_ = _139_ & _017_;
  assign _111_ = _109_ & _110_;
  assign _019_ = _016_ & _018_;
  assign _020_ = _015_ & _019_;
  assign _021_ = _129_ & _020_;
  assign _022_ = ~(_149_ & _021_);
  assign _023_ = _014_ & _022_;
  assign _024_ = ~(_127_ & _162_);
  assign _025_ = _165_ & _024_;
  assign _026_ = _025_ | ~(_120_);
  assign _027_ = _119_ & _026_;
  assign _028_ = ~(_128_ & _162_);
  assign _112_ = prev_solar_gen[12] & ~(solar_generation[12]);
  assign _029_ = ~(_005_ & _028_);
  assign _030_ = _113_ & _029_;
  assign _031_ = ~(_112_ | _030_);
  assign _032_ = ~(_111_ ^ _031_);
  assign _033_ = ~(_114_ & _029_);
  assign _034_ = ~(_008_ & _033_);
  assign _035_ = _107_ & _034_;
  assign _036_ = ~(_107_ ^ _034_);
  assign _037_ = ~(_113_ ^ _029_);
  assign _038_ = ~(_118_ ^ _027_);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) solar_normal <= 1'h1;
    else solar_normal <= _002_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) solar_drop <= 1'h0;
    else solar_drop <= _001_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) solar_critical_drop <= 1'h0;
    else solar_critical_drop <= _000_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[0] <= 1'h0;
    else prev_solar_gen[0] <= solar_generation[0];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[1] <= 1'h0;
    else prev_solar_gen[1] <= solar_generation[1];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[2] <= 1'h1;
    else prev_solar_gen[2] <= solar_generation[2];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[3] <= 1'h0;
    else prev_solar_gen[3] <= solar_generation[3];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[4] <= 1'h0;
    else prev_solar_gen[4] <= solar_generation[4];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[5] <= 1'h0;
    else prev_solar_gen[5] <= solar_generation[5];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[6] <= 1'h1;
    else prev_solar_gen[6] <= solar_generation[6];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[7] <= 1'h1;
    else prev_solar_gen[7] <= solar_generation[7];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[8] <= 1'h1;
    else prev_solar_gen[8] <= solar_generation[8];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[9] <= 1'h0;
    else prev_solar_gen[9] <= solar_generation[9];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[10] <= 1'h0;
    else prev_solar_gen[10] <= solar_generation[10];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[11] <= 1'h1;
    else prev_solar_gen[11] <= solar_generation[11];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[12] <= 1'h0;
    else prev_solar_gen[12] <= solar_generation[12];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[13] <= 1'h0;
    else prev_solar_gen[13] <= solar_generation[13];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[14] <= 1'h0;
    else prev_solar_gen[14] <= solar_generation[14];
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/solar_monitor.v:21.5-39.8" *)
  always @(posedge clk, posedge reset)
    if (reset) prev_solar_gen[15] <= 1'h0;
    else prev_solar_gen[15] <= solar_generation[15];
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:7.1-52.10" *)
module transformer_monitor(clk, reset, transformer_loading_percent, transformer_normal, transformer_warning, transformer_critical, transformer_overload);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:12.24-12.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:13.24-13.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:14.24-14.51" *)
  input [15:0] transformer_loading_percent;
  wire [15:0] transformer_loading_percent;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:15.24-15.42" *)
  output transformer_normal;
  reg transformer_normal;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:16.24-16.43" *)
  output transformer_warning;
  reg transformer_warning;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:17.24-17.44" *)
  output transformer_critical;
  reg transformer_critical;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:18.24-18.44" *)
  output transformer_overload;
  reg transformer_overload;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  wire _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  wire _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  wire _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  assign _04_ = ~(transformer_loading_percent[11] | transformer_loading_percent[7]);
  assign _05_ = _04_ & ~(transformer_loading_percent[10]);
  assign _14_ = ~(transformer_loading_percent[2] | transformer_loading_percent[4]);
  assign _15_ = _14_ & ~(transformer_loading_percent[3]);
  assign _16_ = _11_ & _13_;
  assign _17_ = _11_ & _15_;
  assign _02_ = ~(_16_ | _17_);
  assign _18_ = transformer_loading_percent[4] & ~(transformer_loading_percent[5]);
  assign _19_ = _12_ & _18_;
  assign _01_ = _16_ & ~(_19_);
  assign _20_ = transformer_loading_percent[3] & transformer_loading_percent[1];
  assign _21_ = transformer_loading_percent[2] & _20_;
  assign _06_ = ~(transformer_loading_percent[15] | transformer_loading_percent[13]);
  assign _22_ = _19_ & _21_;
  assign _23_ = ~(transformer_loading_percent[0] & _22_);
  assign _00_ = ~(_16_ & _23_);
  assign _03_ = _19_ & ~(_00_);
  assign _07_ = ~(transformer_loading_percent[12] | transformer_loading_percent[14]);
  assign _08_ = ~(transformer_loading_percent[9] | transformer_loading_percent[8]);
  assign _09_ = _07_ & _08_;
  assign _10_ = _06_ & _09_;
  assign _11_ = _05_ & _10_;
  assign _12_ = transformer_loading_percent[6] & ~(transformer_loading_percent[7]);
  assign _13_ = ~(transformer_loading_percent[5] & _12_);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  always @(posedge clk, posedge reset)
    if (reset) transformer_normal <= 1'h1;
    else transformer_normal <= _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  always @(posedge clk, posedge reset)
    if (reset) transformer_warning <= 1'h0;
    else transformer_warning <= _03_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  always @(posedge clk, posedge reset)
    if (reset) transformer_critical <= 1'h0;
    else transformer_critical <= _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/transformer_monitor.v:21.5-50.8" *)
  always @(posedge clk, posedge reset)
    if (reset) transformer_overload <= 1'h0;
    else transformer_overload <= _02_;
endmodule

(* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:7.1-59.10" *)
module voltage_monitor(clk, reset, voltage, voltage_normal, voltage_low, voltage_high, voltage_critical, voltage_severity);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:13.24-13.27" *)
  input clk;
  wire clk;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:14.24-14.29" *)
  input reset;
  wire reset;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:15.24-15.31" *)
  input [15:0] voltage;
  wire [15:0] voltage;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:16.24-16.38" *)
  output voltage_normal;
  reg voltage_normal;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:17.24-17.35" *)
  output voltage_low;
  reg voltage_low;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:18.24-18.36" *)
  output voltage_high;
  reg voltage_high;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:19.24-19.40" *)
  output voltage_critical;
  reg voltage_critical;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:20.24-20.40" *)
  output [1:0] voltage_severity;
  wire [1:0] voltage_severity;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  wire _00_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  wire _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  wire _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  wire _03_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  wire [1:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  assign _05_ = ~(voltage[15] | voltage[14]);
  assign _06_ = ~(voltage[13] | voltage[11]);
  assign _15_ = ~(voltage[7] | voltage[5]);
  assign _16_ = ~(voltage[9] | voltage[6]);
  assign _17_ = _16_ & ~(voltage[8]);
  assign _18_ = _15_ & _17_;
  assign _19_ = _14_ & _18_;
  assign _20_ = ~(_08_ & _19_);
  assign _01_ = _10_ & _20_;
  assign _21_ = voltage[9] & voltage[8];
  assign _22_ = voltage[7] & _21_;
  assign _23_ = voltage[1] & voltage[2];
  assign _07_ = _06_ & ~(voltage[12]);
  assign _24_ = voltage[3] | _23_;
  assign _25_ = voltage[4] & voltage[5];
  assign _26_ = _24_ & _25_;
  assign _27_ = voltage[6] | _26_;
  assign _28_ = ~(_22_ & _27_);
  assign _02_ = _09_ & _28_;
  assign _29_ = _09_ ? _28_ : _20_;
  assign _03_ = ~_29_;
  assign _30_ = ~(voltage[4] | voltage[3]);
  assign _31_ = ~(voltage[6] | voltage[5]);
  assign _08_ = _05_ & _07_;
  assign _32_ = ~(_30_ & _31_);
  assign _33_ = voltage[2] | _32_;
  assign _34_ = ~(_22_ & _33_);
  assign _00_ = _09_ & _34_;
  assign _04_[0] = _29_ & ~(_00_);
  assign _09_ = _08_ & ~(voltage[10]);
  assign _10_ = ~_09_;
  assign _11_ = voltage[1] & voltage[0];
  assign _12_ = voltage[2] | _11_;
  assign _13_ = voltage[4] & voltage[3];
  assign _14_ = ~(_12_ & _13_);
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) voltage_normal <= 1'h1;
    else voltage_normal <= _03_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) voltage_low <= 1'h0;
    else voltage_low <= _02_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) voltage_high <= 1'h0;
    else voltage_high <= _01_;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) voltage_critical <= 1'h0;
    else voltage_critical <= _00_;
  reg \voltage_severity_reg[0] ;
  (* src = "d:/gridguard/GRIDGUARD_FPGA/rtl/voltage_monitor.v:23.5-57.8" *)
  always @(posedge clk, posedge reset)
    if (reset) \voltage_severity_reg[0]  <= 1'h0;
    else \voltage_severity_reg[0]  <= _04_[0];
  assign voltage_severity[0] = \voltage_severity_reg[0] ;
  assign _04_[1] = _00_;
  assign voltage_severity[1] = voltage_critical;
endmodule
